### ISSUE TITLE
default base url

### ISSUE THREAD

**Issue by adulau** [MISP/misp-packer#1]
Could we setup a default base url based on the configuration of the VM?

https://github.com/MISP/misp-packer/blob/c1bdfc9b54d362f0239f87d670caec859d2afb66/scripts/bootstrap.sh#L19

**Comment by cedricbonhomme** [comment]
Yes. We can add a variable MISP_BASEURL in the misp.json file.
Something like I did here, in three steps:

- https://github.com/monarc-project/monarc-packer/blob/master/monarc.json#L7
- https://github.com/monarc-project/monarc-packer/blob/master/monarc.json#L63
- https://github.com/monarc-project/monarc-packer/blob/master/scripts/bootstrap.sh#L93

But it won't have to be an environment variable. (It is just on my system I generally have the GitHub auth token as an env variable.)

I think, this is a good solution. I'll test. For the moment I do not see a more cleaver way of doing this.

**Comment by adulau** [comment]
Simpler fix ca563becc0a8c80556299627b2018ef79ece2ece ;-)

**Comment by cedricbonhomme** [comment]
Indeed :-) I thought you wanted to keep it configurable.
