### ISSUE TITLE
many error log when running MISP configuration

### ISSUE THREAD

**Issue by derekha2010** [MISP/misp-packer#10]
Platform: Win10

I'm facing many error log when running into MISP configuration block like below, is it related to MISP version not sync with the version of bootstrap script?
> virtualbox-iso: --- MISP configuration ---
virtualbox-iso: [31;4mNotice Error:[0m Array to string conversion in [/var/www/MISP/app/Model/Server.php, line 3286]
virtualbox-iso: [31;4mNotice Error:[0m Array to string conversion in [/var/www/MISP/app/Model/Server.php, line 3286]
...

**Comment by SteveClement** [comment]
Hmmm, ok I will see if this is still the case. Quite some updates have been made in the meantime.

**Comment by SteveClement** [comment]
This can be ignored for now. Will be fixed in next release cycle.
