### ISSUE TITLE
Ubuntu Image has been removed from the public site

### ISSUE THREAD

**Issue by PyNutter** [MISP/misp-packer#13]
The image referenced in the misp.json file has now been removed from the public Ubuntu site.. so the image name and hash need to be updated!  (in the 18.04 branch)

Also, at the end of the packer build, the MISP LICENSE file is missing?

**Comment by PyNutter** [comment]
deploy.sh contains the code that would put the MISP LICENSE file in the expected location, but Packer never calls it?

**Comment by SteveClement** [comment]
Thanks I will see to it...

**Comment by SteveClement** [comment]
Fixed, there also is a vbox build script now that handles the LICENSE file...
