### ISSUE TITLE
misp user doesn't exist

### ISSUE THREAD

**Issue by 0xtf** [MISP/misp-packer#8]
Script calls for misp user for both viper and misp-dashboard, but the user "misp" is not created anywhere in the script. 

User needs to be created or misp-dashboard and viper need to run as www-data.

**Comment by 0xtf** [comment]
misp-dashboard apache configuration also calls for "misp" which will make Apache fail to start.

**Comment by derekha2010** [comment]
AFAIK the misp user should created over misp.json by using Packer
https://github.com/MISP/misp-packer/blob/4d45001359a87b8b51ca45dd8553d3bd407d1c16/misp.json#L47-L48

**Comment by SteveClement** [comment]
Testing the latest version to see if this still persists.

**Comment by SteveClement** [comment]
But @derekha2010 is right, the json has all the user creation stuff already included, it should just work.

Tested it on Packer 1.3.5 and all works as expected.
